### ISSUE TITLE
2 integrations already existing

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Contributions-Symfony-RulerBundle#2]
I just discover this https://github.com/rezzza/RulerBundle and this https://github.com/ulabox/UlaboxRulerBundle 

for information

**Comment by stephpy** [comment]
Rezzza/RulerBundle isn't maintained.

**Comment by stephpy** [comment]
And this other one doesn't use `Hoa/Ruler` but `ruler/ruler`. https://github.com/ulabox/UlaboxRulerBundle/blob/master/composer.json
